Exit with error when package fails the check

diff --git a/pkg-check/action.yml b/pkg-check/action.yml
--- a/pkg-check/action.yml
+++ b/pkg-check/action.yml
@@ -124,6 +124,8 @@ runs:
                echo " --------------------------------- "
               fi
             done
+            echo "::error ::ERROR: package $PACKAGE check failed"
+            exit 1
         fi
         echo '::endgroup::'
       shell: bash
